"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    RISK_FIELD_NUMBER: builtins.int
    x: builtins.float = ...
    y: builtins.float = ...
    risk: builtins.float = ...
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        risk: builtins.float = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["risk", b"risk", "x", b"x", "y", b"y"],
    ) -> None: ...

global___Point = Point

class Index(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDX_X_FIELD_NUMBER: builtins.int
    IDX_Y_FIELD_NUMBER: builtins.int
    idx_x: builtins.int = ...
    idx_y: builtins.int = ...
    def __init__(
        self,
        *,
        idx_x: builtins.int = ...,
        idx_y: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["idx_x", b"idx_x", "idx_y", b"idx_y"],
    ) -> None: ...

global___Index = Index

class CostMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MIN_X_FIELD_NUMBER: builtins.int
    MAX_X_FIELD_NUMBER: builtins.int
    MIN_Y_FIELD_NUMBER: builtins.int
    MAX_Y_FIELD_NUMBER: builtins.int
    RESOLUTION_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    IDX_FIELD_NUMBER: builtins.int
    min_x: builtins.float = ...
    max_x: builtins.float = ...
    min_y: builtins.float = ...
    max_y: builtins.float = ...
    resolution: builtins.float = ...
    @property
    def points(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Point
    ]: ...
    @property
    def idx(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Index
    ]: ...
    def __init__(
        self,
        *,
        min_x: builtins.float = ...,
        max_x: builtins.float = ...,
        min_y: builtins.float = ...,
        max_y: builtins.float = ...,
        resolution: builtins.float = ...,
        points: typing.Optional[typing.Iterable[global___Point]] = ...,
        idx: typing.Optional[typing.Iterable[global___Index]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "idx",
            b"idx",
            "max_x",
            b"max_x",
            "max_y",
            b"max_y",
            "min_x",
            b"min_x",
            "min_y",
            b"min_y",
            "points",
            b"points",
            "resolution",
            b"resolution",
        ],
    ) -> None: ...

global___CostMap = CostMap
