"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SolverParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MAX_ITER_FIELD_NUMBER: builtins.int
    MAP_RESOLUTION_FIELD_NUMBER: builtins.int
    max_iter: builtins.float = ...
    map_resolution: builtins.float = ...
    def __init__(
        self,
        *,
        max_iter: builtins.float = ...,
        map_resolution: builtins.float = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "map_resolution", b"map_resolution", "max_iter", b"max_iter"
        ],
    ) -> None: ...

global___SolverParams = SolverParams
