"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import cost_map_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import kinematic_model_pb2
import params_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Polygon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERTEX_NUM_FIELD_NUMBER: builtins.int
    VERTEX_PTS_FIELD_NUMBER: builtins.int
    vertex_num: builtins.int = ...
    @property
    def vertex_pts(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        cost_map_pb2.Pos2D
    ]: ...
    def __init__(
        self,
        *,
        vertex_num: builtins.int = ...,
        vertex_pts: typing.Optional[typing.Iterable[cost_map_pb2.Pos2D]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "vertex_num", b"vertex_num", "vertex_pts", b"vertex_pts"
        ],
    ) -> None: ...

global___Polygon = Polygon

class MapBound(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MAX_X_FIELD_NUMBER: builtins.int
    MIN_X_FIELD_NUMBER: builtins.int
    MAX_Y_FIELD_NUMBER: builtins.int
    MIN_Y_FIELD_NUMBER: builtins.int
    max_x: builtins.float = ...
    min_x: builtins.float = ...
    max_y: builtins.float = ...
    min_y: builtins.float = ...
    def __init__(
        self,
        *,
        max_x: builtins.float = ...,
        min_x: builtins.float = ...,
        max_y: builtins.float = ...,
        min_y: builtins.float = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "max_x", b"max_x", "max_y", b"max_y", "min_x", b"min_x", "min_y", b"min_y"
        ],
    ) -> None: ...

global___MapBound = MapBound

class PlanProblem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INIT_STATE_FIELD_NUMBER: builtins.int
    GOAL_STATE_FIELD_NUMBER: builtins.int
    VEHICLE_PARAM_FIELD_NUMBER: builtins.int
    OBSTACLE_NUM_FIELD_NUMBER: builtins.int
    OBSTACLE_LIST_FIELD_NUMBER: builtins.int
    MAP_BOUND_FIELD_NUMBER: builtins.int
    @property
    def init_state(self) -> kinematic_model_pb2.StateVar: ...
    @property
    def goal_state(self) -> kinematic_model_pb2.StateVar: ...
    @property
    def vehicle_param(self) -> kinematic_model_pb2.VehicleParam: ...
    obstacle_num: builtins.int = ...
    @property
    def obstacle_list(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Polygon
    ]: ...
    @property
    def map_bound(self) -> global___MapBound: ...
    def __init__(
        self,
        *,
        init_state: typing.Optional[kinematic_model_pb2.StateVar] = ...,
        goal_state: typing.Optional[kinematic_model_pb2.StateVar] = ...,
        vehicle_param: typing.Optional[kinematic_model_pb2.VehicleParam] = ...,
        obstacle_num: builtins.int = ...,
        obstacle_list: typing.Optional[typing.Iterable[global___Polygon]] = ...,
        map_bound: typing.Optional[global___MapBound] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "goal_state",
            b"goal_state",
            "init_state",
            b"init_state",
            "map_bound",
            b"map_bound",
            "vehicle_param",
            b"vehicle_param",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "goal_state",
            b"goal_state",
            "init_state",
            b"init_state",
            "map_bound",
            b"map_bound",
            "obstacle_list",
            b"obstacle_list",
            "obstacle_num",
            b"obstacle_num",
            "vehicle_param",
            b"vehicle_param",
        ],
    ) -> None: ...

global___PlanProblem = PlanProblem

class PlanRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONTROL_LIST_FIELD_NUMBER: builtins.int
    STATE_LIST_FIELD_NUMBER: builtins.int
    SOLVE_SUCCESS_FIELD_NUMBER: builtins.int
    COST_MAP_FIELD_NUMBER: builtins.int
    @property
    def control_list(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        kinematic_model_pb2.ControlVar
    ]: ...
    @property
    def state_list(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        kinematic_model_pb2.StateVar
    ]: ...
    solve_success: builtins.bool = ...
    @property
    def cost_map(self) -> cost_map_pb2.CostMap: ...
    def __init__(
        self,
        *,
        control_list: typing.Optional[
            typing.Iterable[kinematic_model_pb2.ControlVar]
        ] = ...,
        state_list: typing.Optional[
            typing.Iterable[kinematic_model_pb2.StateVar]
        ] = ...,
        solve_success: builtins.bool = ...,
        cost_map: typing.Optional[cost_map_pb2.CostMap] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["cost_map", b"cost_map"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "control_list",
            b"control_list",
            "cost_map",
            b"cost_map",
            "solve_success",
            b"solve_success",
            "state_list",
            b"state_list",
        ],
    ) -> None: ...

global___PlanRes = PlanRes

class SolverInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PLAN_PROBLEM_FIELD_NUMBER: builtins.int
    SOLVER_PARAMS_FIELD_NUMBER: builtins.int
    @property
    def plan_problem(self) -> global___PlanProblem: ...
    @property
    def solver_params(self) -> params_pb2.SolverParams: ...
    def __init__(
        self,
        *,
        plan_problem: typing.Optional[global___PlanProblem] = ...,
        solver_params: typing.Optional[params_pb2.SolverParams] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "plan_problem", b"plan_problem", "solver_params", b"solver_params"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "plan_problem", b"plan_problem", "solver_params", b"solver_params"
        ],
    ) -> None: ...

global___SolverInput = SolverInput
