syntax = "proto3";

package params;

message HybridAStarGCost{
    double reverse_cost = 1;
    double head_change_cost = 2;
}

message HybridAStarParams{
    int32 max_iter = 1;
    double expand_s = 2;
    int32 expand_step_num = 3;
    double max_steer_angle = 4;
    int32 search_front_num = 5;
    int32 search_back_num = 6;
    double rs_radius = 7;
    double rs_step_size = 8;
    double wheel_base = 9;
    double node_resolution_x = 10;
    double node_resolution_y = 11;
    double node_resolution_theta = 12;
    HybridAStarGCost g_cost = 13;
}

message PiecewiseJerkParams {
    double max_iter = 1;
    double min_v = 2;
    double max_v = 3;
    double min_acc = 4;
    double max_acc = 5;
    double w_jerk = 6;
    double w_acc = 7;
    double w_s_ref = 8;
    double w_v_ref = 9;
    double w_s_end = 10;
    double w_v_end = 11;
    double w_a_end = 12;
}

message OBCAParams {
    double ref_weight = 1;
    double smooth_weight = 2;
    double control_weight = 3;
    int32 ipopt_max_iter = 4;
    double ipopt_tol = 5;
    double ipopt_acceptable_tol = 6;
    int32 ipopt_acceptable_iter = 7;
    string linear_solver = 8;
}

message RDAParams {
    int32 max_iter = 1;
    double convergence_tolerance = 2;
    double penalty_weight = 3;
    bool use_warm_start = 4;
    double l1_weight = 5;
    double w_s = 6;
    double w_u = 7;
}

message SolverParams {
    double max_iter = 1;
    double map_resolution = 2;
    HybridAStarParams hybrid_a_star_param = 3;
    PiecewiseJerkParams piesewise_jerk_params = 4;
    OBCAParams obca_params = 5;
    RDAParams rda_params = 6;
    string backend_solver = 7;
    double dt = 8;
}