max_iter: 50
map_resolution: 0.3 # meters


hybrid_a_star_param: # NOTE: the following key's name MUST be the same as those in protobuf/params.proto
  max_iter: 20 # iterations
  expand_s: 1.5 # m
  expand_step_num: 5 # number of steps to expand for collision check
  max_steer_angle: 0.75 # rad
  search_front_num: 5 # number of search front
  search_back_num: 3 # number of search back
  rs_radius: 15 # meters (in this circle, try RS curve to reach the goal)
  rs_step_size: 0.3 # meters (step size of RS path for collision check)
  wheel_base: 2.5 # meters
  node_resolution_x: 0.5 # meters
  node_resolution_y: 0.5 # meters
  node_resolution_theta: 10 # degrees
  g_cost:
    reverse_cost: 1.0
    head_change_cost: 0.5 

piesewise_jerk_params:
  max_iter: 100 # m/s^2
  min_acc: -2.5 # m/s^2
  max_acc: 2.5 # m/s^2
  max_v: 5.0 # m/s
  min_v: -5.0 # m/s
  # ======= weight =======
  w_jerk: 15.0
  w_acc: 10.0
  w_s_ref: 10.0
  w_v_ref: 5.0
  w_s_end: 50.0
  w_v_end: 50.0
  w_a_end: 50.0