#include "planner/mppi/mppi_planner.h"

#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <utility>
#include <vector>

namespace planning::mppi {
namespace {

constexpr double kPi                 = 3.14159265358979323846;
constexpr double kTwoPi              = 2.0 * kPi;
constexpr double kMinimumTemperature = 1.0e-9;

struct Sample {
    std::vector<Control> noise;
    double               cost = 0.0;
};

}   // namespace

MppiPlanner::MppiPlanner(MppiConfig config)
    : config_(std::move(config))
    , nominal_controls_(config_.horizon)
    , random_generator_(config_.random_seed) {
    if (config_.horizon == 0 || config_.num_samples == 0 || config_.num_iterations == 0) {
        throw std::invalid_argument("MPPI horizon, samples, and iterations must be positive");
    }
    if (config_.time_step <= 0.0 || config_.wheelbase <= 0.0 || config_.temperature <= 0.0) {
        throw std::invalid_argument("MPPI time step, wheelbase, and temperature must be positive");
    }
    if (config_.steering_noise <= 0.0 || config_.acceleration_noise <= 0.0) {
        throw std::invalid_argument("MPPI sampling standard deviations must be positive");
    }
    if (config_.control_rate_weight < 0.0) {
        throw std::invalid_argument("MPPI control rate weight must be non-negative");
    }
    if (config_.noise_smoothing < 0.0 || config_.noise_smoothing >= 1.0) {
        throw std::invalid_argument("MPPI noise smoothing must be in the range [0, 1)");
    }
    if (config_.obstacle_softening <= 0.0) { throw std::invalid_argument("MPPI obstacle softening must be positive"); }
    if (config_.road_boundary_weight < 0.0 || config_.road_right_limit >= config_.road_left_limit) {
        throw std::invalid_argument("MPPI road boundary configuration is invalid");
    }
}

PlanResult MppiPlanner::Plan(const VehicleState& initial_state, const std::vector<VehicleState>& reference,
                             const std::vector<CircularObstacle>& obstacles) {
    ValidateInputs(reference);
    ShiftControlSequence();

    std::normal_distribution<double> steering_distribution(0.0, config_.steering_noise);
    std::normal_distribution<double> acceleration_distribution(0.0, config_.acceleration_noise);
    // Correlation coefficient of the temporally smoothed sampling noise. With
    // smoothing the noise is generated by an AR(1) process
    //   noise_k = rho * noise_{k-1} + sqrt(1 - rho^2) * white_k
    // which keeps the marginal variance but removes high-frequency jitter.
    const double noise_smoothing = config_.noise_smoothing;
    const double noise_scale     = std::sqrt(1.0 - noise_smoothing * noise_smoothing);

    for (std::size_t iteration = 0; iteration < config_.num_iterations; ++iteration) {
        std::vector<Sample> samples(config_.num_samples);
        double              minimum_cost = std::numeric_limits<double>::infinity();

        for (Sample& sample : samples) {
            sample.noise.resize(config_.horizon);
            std::vector<Control> sampled_controls(config_.horizon);
            double               exploration_cost            = 0.0;
            double               previous_steering_noise     = 0.0;
            double               previous_acceleration_noise = 0.0;

            for (std::size_t step = 0; step < config_.horizon; ++step) {
                Control&     noise              = sample.noise[step];
                const double white_steering     = steering_distribution(random_generator_);
                const double white_acceleration = acceleration_distribution(random_generator_);
                noise.steering     = noise_smoothing * previous_steering_noise + noise_scale * white_steering;
                noise.acceleration = noise_smoothing * previous_acceleration_noise + noise_scale * white_acceleration;
                previous_steering_noise     = noise.steering;
                previous_acceleration_noise = noise.acceleration;

                sampled_controls[step].steering = Clamp(
                    nominal_controls_[step].steering + noise.steering, config_.min_steering, config_.max_steering);
                sampled_controls[step].acceleration = Clamp(nominal_controls_[step].acceleration + noise.acceleration,
                                                            config_.min_acceleration,
                                                            config_.max_acceleration);

                exploration_cost += config_.temperature * config_.control_weight *
                                    (nominal_controls_[step].steering * noise.steering /
                                         (config_.steering_noise * config_.steering_noise) +
                                     nominal_controls_[step].acceleration * noise.acceleration /
                                         (config_.acceleration_noise * config_.acceleration_noise));
            }

            const std::vector<VehicleState> states = Rollout(initial_state, sampled_controls);
            sample.cost  = ComputeCost(states, sampled_controls, reference, obstacles) + exploration_cost;
            minimum_cost = std::min(minimum_cost, sample.cost);
        }

        std::vector<double> weights(samples.size(), 0.0);
        double              weight_sum = 0.0;
        // Self-calibrating weighting temperature. The cumulative cost scale
        // depends on the horizon, cost weights, and current state, so a fixed
        // temperature collapses the importance weights onto a single sample
        // (random steering updates) when costs are large, or makes them nearly
        // uniform (no learning) when costs are small. Using the excess cost at
        // the 10th percentile as the temperature scale keeps a meaningful set
        // of low-cost samples contributing in every regime.
        std::vector<double> sorted_costs;
        sorted_costs.reserve(samples.size());
        for (const Sample& sample : samples) { sorted_costs.push_back(sample.cost); }
        std::sort(sorted_costs.begin(), sorted_costs.end());
        const double p10_cost = sorted_costs[samples.size() / 10];
        const double temperature =
            std::max(std::max(config_.temperature, kMinimumTemperature), 0.4 * std::max(0.0, p10_cost - minimum_cost));
        for (std::size_t sample_index = 0; sample_index < samples.size(); ++sample_index) {
            weights[sample_index] = std::exp(-(samples[sample_index].cost - minimum_cost) / temperature);
            weight_sum += weights[sample_index];
        }

        if (weight_sum <= std::numeric_limits<double>::epsilon()) { continue; }
        for (std::size_t step = 0; step < config_.horizon; ++step) {
            Control weighted_noise;
            for (std::size_t sample_index = 0; sample_index < samples.size(); ++sample_index) {
                const double normalized_weight = weights[sample_index] / weight_sum;
                weighted_noise.steering += normalized_weight * samples[sample_index].noise[step].steering;
                weighted_noise.acceleration += normalized_weight * samples[sample_index].noise[step].acceleration;
            }
            nominal_controls_[step].steering = Clamp(
                nominal_controls_[step].steering + weighted_noise.steering, config_.min_steering, config_.max_steering);
            nominal_controls_[step].acceleration =
                Clamp(nominal_controls_[step].acceleration + weighted_noise.acceleration,
                      config_.min_acceleration,
                      config_.max_acceleration);
        }
    }

    PlanResult result;
    result.controls = nominal_controls_;
    result.states   = Rollout(initial_state, result.controls);
    result.cost     = ComputeCost(result.states, result.controls, reference, obstacles);
    if (!result.controls.empty()) { last_applied_control_ = result.controls.front(); }
    return result;
}

void MppiPlanner::Reset() {
    nominal_controls_.assign(config_.horizon, Control{});
    last_applied_control_ = Control{};
    random_generator_.seed(config_.random_seed);
}

double MppiPlanner::NormalizeAngle(double angle) {
    while (angle > kPi) { angle -= kTwoPi; }
    while (angle < -kPi) { angle += kTwoPi; }
    return angle;
}

double MppiPlanner::Clamp(double value, double lower, double upper) {
    return std::max(lower, std::min(value, upper));
}

VehicleState MppiPlanner::Propagate(const VehicleState& state, const Control& control) const {
    const double steering     = Clamp(control.steering, config_.min_steering, config_.max_steering);
    const double acceleration = Clamp(control.acceleration, config_.min_acceleration, config_.max_acceleration);

    VehicleState next_state;
    next_state.x = state.x + state.velocity * std::cos(state.yaw) * config_.time_step;
    next_state.y = state.y + state.velocity * std::sin(state.yaw) * config_.time_step;
    next_state.yaw =
        NormalizeAngle(state.yaw + state.velocity * std::tan(steering) / config_.wheelbase * config_.time_step);
    next_state.velocity =
        Clamp(state.velocity + acceleration * config_.time_step, config_.min_velocity, config_.max_velocity);
    return next_state;
}

std::vector<VehicleState> MppiPlanner::Rollout(const VehicleState&         initial_state,
                                               const std::vector<Control>& controls) const {
    std::vector<VehicleState> states;
    states.reserve(controls.size() + 1);
    states.push_back(initial_state);
    for (const Control& control : controls) { states.push_back(Propagate(states.back(), control)); }
    return states;
}

double MppiPlanner::ComputeCost(const std::vector<VehicleState>& states, const std::vector<Control>& controls,
                                const std::vector<VehicleState>&     reference,
                                const std::vector<CircularObstacle>& obstacles) const {
    double cost = 0.0;
    for (std::size_t step = 1; step < states.size(); ++step) {
        const VehicleState& state            = states[step];
        const VehicleState& target           = reference[std::min(step, reference.size() - 1)];
        const double        delta_x          = state.x - target.x;
        const double        delta_y          = state.y - target.y;
        const double        delta_yaw        = NormalizeAngle(state.yaw - target.yaw);
        const double        delta_velocity   = state.velocity - target.velocity;
        const double        state_multiplier = step + 1 == states.size() ? config_.terminal_weight : 1.0;

        cost += state_multiplier * (config_.position_weight * (delta_x * delta_x + delta_y * delta_y) +
                                    config_.heading_weight * delta_yaw * delta_yaw +
                                    config_.velocity_weight * delta_velocity * delta_velocity);

        // Road-boundary cost: penalize lateral deviation beyond the drivable
        // corridor so obstacle detours stay on the road surface.
        const double lateral = -std::sin(target.yaw) * delta_x + std::cos(target.yaw) * delta_y;
        if (lateral > config_.road_left_limit) {
            const double excess = lateral - config_.road_left_limit;
            cost += config_.road_boundary_weight * excess * excess;
        } else if (lateral < config_.road_right_limit) {
            const double excess = config_.road_right_limit - lateral;
            cost += config_.road_boundary_weight * excess * excess;
        }

        const Control& control = controls[step - 1];
        cost += config_.control_weight *
                (control.steering * control.steering + control.acceleration * control.acceleration);

        // Penalize the change of control between consecutive steps. The first
        // step is anchored to the control actually applied by the previous
        // receding-horizon plan, which keeps the executed trajectory continuous.
        const Control& previous_control   = step == 1 ? last_applied_control_ : controls[step - 2];
        const double   delta_steering     = control.steering - previous_control.steering;
        const double   delta_acceleration = control.acceleration - previous_control.acceleration;
        cost +=
            config_.control_rate_weight * (delta_steering * delta_steering + delta_acceleration * delta_acceleration);

        for (const CircularObstacle& obstacle : obstacles) {
            const double center_distance = std::hypot(state.x - obstacle.x, state.y - obstacle.y);
            const double clearance       = center_distance - obstacle.radius - config_.vehicle_radius;
            if (clearance <= 0.0) {
                cost += config_.collision_cost;
            } else {
                cost += config_.obstacle_weight * std::exp(-clearance / config_.obstacle_softening);
            }
        }
    }
    return cost;
}

void MppiPlanner::ValidateInputs(const std::vector<VehicleState>& reference) const {
    if (reference.empty()) { throw std::invalid_argument("MPPI reference trajectory must not be empty"); }
}

void MppiPlanner::ShiftControlSequence() {
    if (nominal_controls_.empty()) { return; }
    for (std::size_t step = 1; step < nominal_controls_.size(); ++step) {
        nominal_controls_[step - 1] = nominal_controls_[step];
    }
    nominal_controls_.back() =
        nominal_controls_.size() > 1 ? nominal_controls_[nominal_controls_.size() - 2] : Control{};
}

}   // namespace planning::mppi
